// Auto-generated by optimize-images.ts — do not edit manually.
// Provides srcset data for responsive <picture> elements.

export interface ResponsiveImage {
  avifSrcset: string;
  webpSrcset: string;
  src: string;  // fallback (largest WebP)
}

export const images: Record<string, ResponsiveImage> = {
  "maps-1": {
    avifSrcset: "/images/maps-1-320.avif 320w, /images/maps-1-640.avif 640w, /images/maps-1-960.avif 960w, /images/maps-1-1280.avif 1280w",
    webpSrcset: "/images/maps-1-320.webp 320w, /images/maps-1-640.webp 640w, /images/maps-1-960.webp 960w, /images/maps-1-1280.webp 1280w",
    src: "/images/maps-1-1280.webp",
  },
  "maps-2": {
    avifSrcset: "/images/maps-2-320.avif 320w, /images/maps-2-640.avif 640w, /images/maps-2-960.avif 960w, /images/maps-2-1280.avif 1280w",
    webpSrcset: "/images/maps-2-320.webp 320w, /images/maps-2-640.webp 640w, /images/maps-2-960.webp 960w, /images/maps-2-1280.webp 1280w",
    src: "/images/maps-2-1280.webp",
  },
  "maps-3": {
    avifSrcset: "/images/maps-3-320.avif 320w, /images/maps-3-640.avif 640w, /images/maps-3-960.avif 960w, /images/maps-3-1280.avif 1280w",
    webpSrcset: "/images/maps-3-320.webp 320w, /images/maps-3-640.webp 640w, /images/maps-3-960.webp 960w, /images/maps-3-1280.webp 1280w",
    src: "/images/maps-3-1280.webp",
  },
};
